---
- name: Update all Linux hosts
  hosts: all
  become: true
  tasks:
    - name: Update package cache for Ubuntu/Debian-based systems
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Upgrade packages for Ubuntu/Debian-based systems
      apt:
        upgrade: dist
      when: ansible_facts['os_family'] == 'Debian'

    - name: Update package cache for RedHat/Fedora-based systems
      yum:
        update_cache: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Upgrade packages for RedHat/Fedora-based systems
      yum:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'

